### ISSUE TITLE
Update `stage_input` subworkflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/argo-modules#24]
updating pre/sample module to add support to new dnaaln workflow in nf-core framework
PR: https://github.com/icgc-argo-workflows/argo-modules/pull/22 https://github.com/icgc-argo-workflows/argo-modules/pull/27

**Comment by lindaxiang** [comment]
Update `stage_input` subworkflow to incorporate the modules:
- song_score_download subworkflow
- input_check local subworkflow

So that this subworkflow will address the complex logics regarding to various inputs/process/output scenario:
1. local input, local processing and local output
- user provide input as a csv file including metadata in both csv format and json format
- user provide data files from local storage
- process the data locally
- output to local
2. rdpc input, local processing and local output
- user provide api_token, study_id and analysis_ids
- download data from rdpc song/score
- process the data locally
- output to local
3. rdpc input and rdpc processing and rdpc output
- user provide api_token, study_id and analysis_ids
- download data from rdpc song/score
- process the data in rdpc
- upload output to rdpc song/score

**Comment by justincorrigible** [comment]
Closing as completed
