### ISSUE TITLE
Few bugs and feature improvement for stage_input & checkinput

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/argo-modules#28]
- [ ] stage_input / output: meta_analysis should have `.first()` instead of meta_files
- [ ] checkinput / prealnqc set defaults for read_group_count and analysis_type
- [ ] dnaaln, dnaalnqc and germlinevar should have defaults for analysis_type
- [ ] stage_input will accept params: study_id, analysis_ids, samplesheet, it will also handle the logics to support multiple analysis inputs. 
- [ ] checkinput / prealnqc single_end use `row.single_end.toBoolean()`

**Comment by lindaxiang** [comment]
One more feature improvement
- [ ] checkinput / prealnqc: remove requirement for field `crai`, auto-generate the index file if it is missing.

**Comment by justincorrigible** [comment]
Closing as completed
