### ISSUE TITLE
Create a nf-core subworkflow Merge_Sort_Dup

### ISSUE THREAD

**Issue by guanqiaofeng** [icgc-argo-workflows/argo-modules#31]

**Comment by guanqiaofeng** [comment]
@guanqiaofeng

**Comment by guanqiaofeng** [comment]
Development note:
1. nf-core software is not running properly in my local environment. Using docker image for development. 
```
docker pull nfcore/base
docker run -it --name my_workflow_dev -v /Users/gfeng/Documents/Work/nf-core/subworkflows:/Users/gfeng/Documents/Work/nf-core/subworkflows nfcore/base
```
2.

**Comment by guanqiaofeng** [comment]
## Development
### 1. Repository set up and docker image set up
#### (1) Set up github repository 'Merge_Sort_Dup'
#### (2) Cone git repository in local VS Code
#### (3) Create dev branch and locate to dev branch
```
git branch dev
git checkout dev
```
#### (4) Run docker image
```
docker run -it -v $(pwd):/workspace -w /workspace nf-core-docker /bin/bash
```
Run a Docker container, mounting the repository's directory as a volume inside the container. Any changes made will be reflected in the local repository directory outside the container, thanks to the volume mount.

**Comment by guanqiaofeng** [comment]
1. Create a branch `merge_sort_dup_subworkflow` from main in git repository
2. Clone git repository to VS Code environment
3. Set docker environment `docker run -it -v $(pwd):/workspace -w /workspace nf-core-nextflow-docker /bin/bash`
4. change to `merge_sort_dup_subworkflow` branch
5. Create modules
```
nf-core modules create samtools/merge
nf-core modules create samtools/convert
nf-core modules create biobambam/bammarkduplicates2
nf-core modules create tar
```
6. Update modules with git repositories (exact copy of 3 files: environment.yml, main.nf, meta.yml)
samtools/merge: https://github.com/nf-core/modules/tree/master/modules/nf-core/samtools/merge
samtools/convert: https://github.com/nf-core/modules/tree/master/modules/nf-core/samtools/convert
biobambam/bammarkduplicates2: https://github.com/nf-core/modules/tree/master/modules/nf-core/biobambam/bammarkduplicates2

**Comment by justincorrigible** [comment]
Closing as done
